version: "3.9"
services:
  dev:
    # Will build ./Dockerfile
    # This Dockerfile is for development
    build:
      context: .
      dockerfile: ./Dockerfile.pipeline
    volumes:
      - ./:/VrtParserPipeline
    image: sridhar1ga/audio_tagging_parser:latest